# Static Inventory (INI Format)

[webservers]
web1 ansible_host=192.168.56.11
web2 ansible_host=192.168.56.13
web3 ansible_host=192.168.56.14

[dbservers]
db1 ansible_host=192.168.56.12
db2 ansible_host=192.168.56.15

[loadbalancers]
lb1 ansible_host=192.168.56.16

# Group of groups (children)
[production:children]
webservers
dbservers
loadbalancers

# Variables for all webservers
[webservers:vars]
http_port=80
max_clients=200
ansible_user=ubuntu

# Variables for all dbservers
[dbservers:vars]
db_port=5432
ansible_user=postgres

# Variables for ALL hosts
[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_ed25519
