---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    webservers:
      vars:
        http_port: 80
      hosts:
        web1:
          ansible_host: 192.168.56.11
        web2:
          ansible_host: 192.168.56.13
    dbservers:
      vars:
        db_port: 5432
      hosts:
        db1:
          ansible_host: 192.168.56.12
    production:
      children:
        webservers:
        dbservers:
